/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMerkleStorageInvalidator,
  IMerkleStorageInvalidatorInterface,
} from "../IMerkleStorageInvalidator";

const _abi = [
  {
    type: "function",
    name: "lastValidated",
    inputs: [
      {
        name: "key",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "index",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "secretHash",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "error",
    name: "AccessDenied",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidProof",
    inputs: [],
  },
] as const;

export class IMerkleStorageInvalidator__factory {
  static readonly abi = _abi;
  static createInterface(): IMerkleStorageInvalidatorInterface {
    return new Interface(_abi) as IMerkleStorageInvalidatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMerkleStorageInvalidator {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IMerkleStorageInvalidator;
  }
}
